package task

import "errors"

var (
	ErrNoTaskMD           = errors.New("task.md not found")
	ErrEmptyBody          = errors.New("task.md body is empty")
	ErrUnsupportedKey     = errors.New("unsupported key")
	ErrDuplicateDepOn     = errors.New("duplicate depends_on entry")
	ErrSelfReference      = errors.New("depends_on contains self-reference")
	ErrInvalidType        = errors.New("invalid type: must be markdown or json")
	ErrDuplicateTool      = errors.New("duplicate tool ID")
	ErrInvalidSchema      = errors.New("invalid JSON schema")
	ErrReservedPath       = errors.New("reserved path detected")
	ErrSymlink            = errors.New("symlinks not allowed")
	ErrNoModel            = errors.New("root task has no effective model")
	ErrSchemaRequired     = errors.New("output.type json requires schema.md")
	ErrSchemaForbidden    = errors.New("schema.md present but output.type is not json")
	ErrMisplacedTask      = errors.New("task.md found outside subtasks/ lineage")
	ErrInvalidToolLine    = errors.New("invalid line in tools.md: expected bullet item")
	ErrCycleDetected      = errors.New("dependency cycle detected")
	ErrDependsOnNotFound  = errors.New("depends_on references non-existent sibling")
	ErrInputTypeMismatch  = errors.New("sibling dependency output type does not match input.type")
	ErrBinaryFile         = errors.New("binary file in context/static")
	ErrInvalidUTF8        = errors.New("invalid UTF-8 in context/static")
	ErrInvalidCachePolicy = errors.New("invalid cache policy: must be auto or never")
	ErrModuleNoSource     = errors.New("module.yaml: source is required")
	ErrModuleInvalidName  = errors.New("module.yaml: invalid source name")
	ErrModuleAndTaskMD    = errors.New("module.yaml and task.md cannot coexist in the same directory")
	ErrModuleUserSubtasks = errors.New("user-authored subtasks not allowed alongside module.yaml")
	ErrEmptyReturnBody    = errors.New("return.md body is empty")
	ErrReturnNoChildren   = errors.New("return.md requires at least one child task")
	ErrShellReturn        = errors.New("shell tasks cannot have return.md")
)
